const DATOS_ES = {

    M1E1: `
#TITULO
Mundo 1 - Etapa 1

#INSTRUCCION
Asocia cada ATRACCIÓN TURÍSTICA al PAÍS que le corresponde

#ENCABEZADO
ATRACCIÓN TURÍSTICA|PAÍS

#DATOS
LA SAGRADA FAMILIA|ESPAÑA
ALHAMBRA|ESPAÑA
MUSEO DEL PRADO|ESPAÑA
PARQUE GÜELL|ESPAÑA
MEZQUITA-CATEDRAL DE CÓRDOBA|ESPAÑA
CATEDRAL DE SANTIAGO DE COMPOSTELA|ESPAÑA
PLAZA MAYOR DE MADRID|ESPAÑA
ACUEDUCTO DE SEGOVIA|ESPAÑA
TEIDE|ESPAÑA
CIUDAD DE LAS ARTES Y LAS CIENCIAS|ESPAÑA
BIG BEN|INGLATERRA
TORRE DE LONDRES|INGLATERRA
PALACIO DE BUCKINGHAM|INGLATERRA
STONEHENGE|INGLATERRA
LONDON EYE|INGLATERRA
ABADÍA DE WESTMINSTER|INGLATERRA
CASTILLO DE WINDSOR|INGLATERRA
MUSEO BRITÁNICO|INGLATERRA
UNIVERSIDAD DE OXFORD|INGLATERRA
UNIVERSIDAD DE CAMBRIDGE|INGLATERRA
TORRE EIFFEL|FRANCIA
MUSEO DEL LOUVRE|FRANCIA
CATEDRAL DE NOTRE-DAME DE PARÍS|FRANCIA
ARCO DE TRIUNFO DE PARÍS|FRANCIA
PALACIO DE VERSALLES|FRANCIA
MONTE SAINT-MICHEL|FRANCIA
BASÍLICA DEL SAGRADO CORAZÓN|FRANCIA
AVENIDA DE LOS CAMPOS ELÍSEOS|FRANCIA
PUENTE DEL GARD|FRANCIA
DISNEYLAND PARÍS|FRANCIA
COLISEO|ITALIA
TORRE DE PISA|ITALIA
CINQUE TERRE|ITALIA
CATEDRAL DE MILÁN|ITALIA
GRAN CANAL DE VENECIA|ITALIA
POMPEYA|ITALIA
GALERÍA UFFIZI|ITALIA
CATEDRAL DE SANTA MARÍA DEL FIORE|ITALIA
COSTA AMALFITANA|ITALIA
FORO ROMANO|ITALIA
`,

    M1E2: `
#TITULO
Mundo 1 - Etapa 2

#INSTRUCCION
Asocia cada CIUDAD al PAÍS que le corresponde

#ENCABEZADO
CIUDAD|PAÍS

#DATOS
MADRID|ESPAÑA
BARCELONA|ESPAÑA
VALENCIA|ESPAÑA
SEVILLA|ESPAÑA
ZARAGOZA|ESPAÑA
MÁLAGA|ESPAÑA
MURCIA|ESPAÑA
PALMA DE MALLORCA|ESPAÑA
LAS PALMAS DE GRAN CANARIA|ESPAÑA
BILBAO|ESPAÑA
LONDRES|INGLATERRA
MANCHESTER|INGLATERRA
BIRMINGHAM|INGLATERRA
LIVERPOOL|INGLATERRA
LEEDS|INGLATERRA
BRISTOL|INGLATERRA
SHEFFIELD|INGLATERRA
NOTTINGHAM|INGLATERRA
NEWCASTLE UPON TYNE|INGLATERRA
OXFORD|INGLATERRA
PARÍS|FRANCIA
MARSELLA|FRANCIA
LYON|FRANCIA
TOULOUSE|FRANCIA
NIZA|FRANCIA
NANTES|FRANCIA
ESTRASBURGO|FRANCIA
MONTPELLIER|FRANCIA
BURDEOS|FRANCIA
LILLE|FRANCIA
ROMA|ITALIA
MILÁN|ITALIA
NAPOLES|ITALIA
TURÍN|ITALIA
PALERMO|ITALIA
GENOVA|ITALIA
BOLONIA|ITALIA
FLORENCIA|ITALIA
BARI|ITALIA
VENECIA|ITALIA
`,

    M1E3: `
#TITULO
Mundo 1 - Etapa 3

#INSTRUCCION
Asocia cada CIUDAD al PAÍS que le corresponde

#ENCABEZADO
CIUDAD|PAÍS

#DATOS
SANTIAGO|CHILE
VALPARAÍSO|CHILE
CONCEPCIÓN|CHILE
LA SERENA|CHILE
COQUIMBO|CHILE
ANTOFAGASTA|CHILE
IQUIQUE|CHILE
ARICA|CHILE
TEMUCO|CHILE
PUERTO MONTT|CHILE
BUENOS AIRES|ARGENTINA
CÓRDOBA|ARGENTINA
ROSARIO|ARGENTINA
MENDOZA|ARGENTINA
LA PLATA|ARGENTINA
MAR DEL PLATA|ARGENTINA
SALTA|ARGENTINA
SAN MIGUEL DE TUCUMÁN|ARGENTINA
SANTA FE|ARGENTINA
NEUQUÉN|ARGENTINA
SÃO PAULO|BRASIL
RÍO DE JANEIRO|BRASIL
BELO HORIZONTE|BRASIL
BRASÍLIA|BRASIL
SALVADOR|BRASIL
FORTALEZA|BRASIL
RECIFE|BRASIL
PORTO ALEGRE|BRASIL
CURITIBA|BRASIL
MANAUS|BRASIL
LIMA|PERÚ
AREQUIPA|PERÚ
TRUJILLO|PERÚ
CHICLAYO|PERÚ
PIURA|PERÚ
CUSCO|PERÚ
IQUITOS|PERÚ
HUANCAYO|PERÚ
TACNA|PERÚ
PUNO|PERÚ
`,

    M1E4: `

#TITULO
Mundo 1 - Etapa 4

#INSTRUCCION
Asocia cada PAÍS al CONTINENTE que le corresponde

#ENCABEZADO
PAÍS|CONTINENTE

#DATOS
ESTADOS UNIDOS|AMÉRICA
CANADÁ|AMÉRICA
MÉXICO|AMÉRICA
BRASIL|AMÉRICA
ARGENTINA|AMÉRICA
CHILE|AMÉRICA
COLOMBIA|AMÉRICA
PERÚ|AMÉRICA
VENEZUELA|AMÉRICA
CUBA|AMÉRICA
CHINA|ASIA
INDIA|ASIA
JAPÓN|ASIA
COREA DEL SUR|ASIA
INDONESIA|ASIA
ARABIA SAUDITA|ASIA
IRÁN|ASIA
TAILANDIA|ASIA
TURQUÍA|ASIA
PAKISTÁN|ASIA
SUDÁFRICA|AFRICA
NIGERIA|AFRICA
EGIPTO|AFRICA
MARRUECOS|AFRICA
ARGELIA|AFRICA
ETIOPÍA|AFRICA
KENIA|AFRICA
GHANA|AFRICA
ANGOLA|AFRICA
TÚNEZ|AFRICA
ALEMANIA|EUROPA
FRANCIA|EUROPA
REINO UNIDO|EUROPA
ITALIA|EUROPA
ESPAÑA|EUROPA
RUSIA|EUROPA
PAÍSES BAJOS|EUROPA
SUECIA|EUROPA
HUNGRÍA|EUROPA
SUIZA|EUROPA
`,

    M1E5: `

#TITULO
Mundo 1 - Etapa 5

#INSTRUCCION
Asocia cada ACCIDENTE GEOGRÁFICO al CONTINENTE que le corresponde

#ENCABEZADO
ACCIDENTE GEOGRÁFICO|CONTINENTE

#DATOS
RÍO AMAZONAS|AMÉRICA
RÍO MISISIPI|AMÉRICA
RÍO ORINOCO|AMÉRICA
RÍO PARANÁ|AMÉRICA
RÍO YUKÓN|AMÉRICA
CORDILLERA DE LOS ANDES|AMÉRICA
MONTAÑAS ROCOSAS|AMÉRICA
SIERRA MADRE|AMÉRICA
MONTES APALACHES|AMÉRICA
CORDILLERA DE ALASKA|AMÉRICA
RÍO YANGTSÉ|ASIA
GANGES|ASIA
RÍO INDO|ASIA
RÍO MEKONG|ASIA
RÍO TIGRIS|ASIA
HIMALAYA|ASIA
CORDILLERA DEL KARAKÓRUM|ASIA
HINDÚ KUSH|ASIA
MONTES URALES|ASIA
CÁUCASO|ASIA
NILO|AFRICA
RÍO CONGO|AFRICA
RÍO NIGER|AFRICA
RÍO ZAMBEZE|AFRICA
RÍO ORANGE|AFRICA
CORDILLERA DEL ATLAS|AFRICA
DRAKENSBERG|AFRICA
MACIZO ETÍOPE|AFRICA
MONTAÑAS RWENZORI|AFRICA
MONTE KILIMANJARO|AFRICA
RÍO DANUBIO|EUROPA
RÍO RIN|EUROPA
RÍO VOLGA|EUROPA
RÍO SENA|EUROPA
RÍO TÁMESIS|EUROPA
ALPES|EUROPA
PIRINEOS|EUROPA
MONTES CÁRPATOS|EUROPA
MONTES APENINOS|EUROPA
MONTES BALCANES|EUROPA
`,
    
    M2E1: `

#TITULO
Mundo 2 - Etapa 1

#INSTRUCCION
Asocia cada PERSONAJE a la SERIE DE TV que corresponde:

#ENCABEZADO
PERSONAJE|SERIE DE TV

#DATOS
RACHEL GREEN|FRIENDS
ROSS GELLER|FRIENDS
MONICA GELLER|FRIENDS
CHANDLER BING|FRIENDS
JOEY TRIBBIANI|FRIENDS
JERRY SEINFELD|SEINFELD
GEORGE COSTANZA|SEINFELD
ELAINE BENES|SEINFELD
COSMO KRAMER|SEINFELD
NEWMAN|SEINFELD
TED MOSBY|HOW I MET YOUR MOTHER
ROBIN SCHERBATSKY|HOW I MET YOUR MOTHER
BARNEY STINSON|HOW I MET YOUR MOTHER
MARSHALL ERIKSEN|HOW I MET YOUR MOTHER
LILY ALDRIN|HOW I MET YOUR MOTHER
PAUL BUCHMAN|MAD ABOUT YOU
JAMIE BUCHMAN|MAD ABOUT YOU
LISA STEMPKE|MAD ABOUT YOU
FRAN DUNPHY|MAD ABOUT YOU
MARK DEBIEVEC|MAD ABOUT YOU
`,

    M2E2: `

#TITULO
Mundo 2 - Etapa 2

#INSTRUCCION
Asocia cada PERSONAJE a la SERIE DE TV que corresponde:

#ENCABEZADO
PERSONAJE|SERIE DE TV

#DATOS
GOKU|DRAGON BALL
VEGETA|DRAGON BALL
GOHAN|DRAGON BALL
PICCOLO|DRAGON BALL
KRILIN|DRAGON BALL
NARUTO UZUMAKI|NARUTO
SASUKE UCHIHA|NARUTO
SAKURA HARUNO|NARUTO
KAKASHI HATAKE|NARUTO
JIRAIYA|NARUTO
SEIYA DE PEGASO|CABALLEROS DEL ZODIACO
SHIRYU DE DRAGÓN|CABALLEROS DEL ZODIACO
HYOGA DE CISNE|CABALLEROS DEL ZODIACO
SHUN DE ANDRÓMEDA|CABALLEROS DEL ZODIACO
IKKI DE FÉNIX|CABALLEROS DEL ZODIACO
GON FREECSS|HUNTER X HUNTER
KILLUA ZOLDYCK|HUNTER X HUNTER
KURAPIKA|HUNTER X HUNTER
LEORIO PARADINIGHT|HUNTER X HUNTER
HISOKA|HUNTER X HUNTER
`,

    M2E3: `

#TITULO
Mundo 2 - Etapa 3

#INSTRUCCION
Asocia cada PERSONAJE a la SERIE DE TV que corresponde:

#ENCABEZADO
PERSONAJE|SERIE DE TV

#DATOS
WALTER WHITE|BREAKING BAD
JESSE PINKMAN|BREAKING BAD
GUSTAVO FRING|BREAKING BAD
HANK SCHRADER|BREAKING BAD
SAUL GOODMAN|BREAKING BAD
MARTY BYRDE|OZARK
WENDY BYRDE|OZARK
RUTH LANGMORE|OZARK
JONAH BYRDE|OZARK
CHARLOTTE BYRDE|OZARK
TONY SOPRANO|THE SOPRANOS
CARMELA SOPRANO|THE SOPRANOS
CHRISTOPHER MOLTISANTI|THE SOPRANOS
PAULIE GUALTIERI|THE SOPRANOS
DOCTORA JENNIFER MELFI|THE SOPRANOS
PABLO ESCOBAR|NARCOS
STEVE MURPHY|NARCOS
JAVIER PEÑA|NARCOS
TATA ESCOBAR|NARCOS
GUSTAVO GAVIRIA|NARCOS
`,

    M2E4: `

#TITULO
Mundo 2 - Etapa 4

#INSTRUCCION
Asocia cada PERSONAJE a la SERIE DE TV que corresponde:

#ENCABEZADO
PERSONAJE|SERIE DE TV

#DATOS
HOMERO SIMPSON|LOS SIMPSON
MARGE SIMPSON|LOS SIMPSON
BART SIMPSON|LOS SIMPSON
LISA SIMPSON|LOS SIMPSON
MAGGIE SIMPSON|LOS SIMPSON
PHILIP J. FRY|FUTURAMA
LEELA|FUTURAMA
BENDER|FUTURAMA
PROFESSOR FARNSWORTH|FUTURAMA
AMY WONG|FUTURAMA
PETER GRIFFIN|PADRE DE FAMILIA
LOIS GRIFFIN|PADRE DE FAMILIA
STEWIE GRIFFIN|PADRE DE FAMILIA
BRIAN GRIFFIN|PADRE DE FAMILIA
CHRIS GRIFFIN|PADRE DE FAMILIA
HÉCTOR REYES|REYES DE LA COLINA
PEGGY REYES|REYES DE LA COLINA
BETO REYES|REYES DE LA COLINA
DIEGO GÓMEZ|REYES DE LA COLINA
BLAS DÁVALOS|REYES DE LA COLINA
`,

    M2E5: `

#TITULO
Mundo 2 - Etapa 5

#INSTRUCCION
Asocia cada PERSONAJE a la SERIE DE TV que corresponde:

#ENCABEZADO
PERSONAJE|SERIE DE TV

#DATOS
JON SNOW|JUEGO DE TRONOS
DAENERYS TARGARYEN|JUEGO DE TRONOS
TYRION LANNISTER|JUEGO DE TRONOS
CERSEI LANNISTER|JUEGO DE TRONOS
ARYA STARK|JUEGO DE TRONOS
RAGNAR LOTHBROK|VIKINGOS
LAGERTHA|VIKINGOS
BJORN IRONSIDE|VIKINGOS
IVAR THE BONELESS|VIKINGOS
ROLLO|VIKINGOS
JACK SHEPHARD|LOST
KATE AUSTEN|LOST
JAMES "SAWYER" FORD|LOST
JOHN LOCKE|LOST
HUGO "HURLEY" REYES|LOST
JONAS KAHNWALD|DARK
MARTHA NIELSEN|DARK
ULRICH NIELSEN|DARK
CHARLOTTE DOPPLER|DARK
CLAUDIA TIEDEMANN|DARK
`,

    M3E1: `

#TITULO
Mundo 3 - Etapa 1

#INSTRUCCION
Asocia las siguientes CANCIONES al GRUPO MUSICAL que le corresponde

#ENCABEZADO
CANCIÓN|GRUPO MUSICAL

#DATOS
HEY JUDE|THE BEATLES
LET IT BE|THE BEATLES
YESTERDAY|THE BEATLES
COME TOGETHER|THE BEATLES
HELP!|THE BEATLES
HERE COMES THE SUN|THE BEATLES
A DAY IN THE LIFE|THE BEATLES
ALL YOU NEED IS LOVE|THE BEATLES
STRAWBERRY FIELDS FOREVER|THE BEATLES
I WANT TO HOLD YOUR HAND|THE BEATLES
BOHEMIAN RHAPSODY|QUEEN
WE WILL ROCK YOU|QUEEN
WE ARE THE CHAMPIONS|QUEEN
ANOTHER ONE BITES THE DUST|QUEEN
SOMEBODY TO LOVE|QUEEN
DON'T STOP ME NOW|QUEEN
RADIO GA GA|QUEEN
UNDER PRESSURE|QUEEN
KILLER QUEEN|QUEEN
CRAZY LITTLE THING CALLED LOVE|QUEEN
ANOTHER BRICK IN THE WALL (PART 2)|PINK FLOYD
COMFORTABLY NUMB|PINK FLOYD
WISH YOU WERE HERE|PINK FLOYD
TIME|PINK FLOYD
MONEY|PINK FLOYD
SHINE ON YOU CRAZY DIAMOND|PINK FLOYD
US AND THEM|PINK FLOYD
ECHOES|PINK FLOYD
BRAIN DAMAGE|PINK FLOYD
THE GREAT GIG IN THE SKY|PINK FLOYD
(I CAN'T GET NO) SATISFACTION|THE ROLLING STONES
PAINT IT BLACK|THE ROLLING STONES
SYMPATHY FOR THE DEVIL|THE ROLLING STONES
GIMME SHELTER|THE ROLLING STONES
START ME UP|THE ROLLING STONES
BROWN SUGAR|THE ROLLING STONES
ANGIE|THE ROLLING STONES
JUMPIN' JACK FLASH|THE ROLLING STONES
WILD HORSES|THE ROLLING STONES
YOU CAN'T ALWAYS GET WHAT YOU WANT|THE ROLLING STONES
`,

    M3E2: `

#TITULO
Mundo 3 - Etapa 2

#INSTRUCCION
Asocia cada GRUPO MUSICAL a su PAÍS de origen

#ENCABEZADO
GRUPO|PAÍS

#DATOS
THE BEATLES|INGLATERRA
THE ROLLING STONES|INGLATERRA
QUEEN|INGLATERRA
PINK FLOYD|INGLATERRA
LED ZEPPELIN|INGLATERRA
THE WHO|INGLATERRA
RADIOHEAD|INGLATERRA
COLDPLAY|INGLATERRA
DEPECHE MODE|INGLATERRA
OASIS|INGLATERRA
THE BEACH BOYS|ESTADOS UNIDOS
METALLICA|ESTADOS UNIDOS
NIRVANA|ESTADOS UNIDOS
GUNS N' ROSES|ESTADOS UNIDOS
THE DOORS|ESTADOS UNIDOS
EAGLES|ESTADOS UNIDOS
RED HOT CHILI PEPPERS|ESTADOS UNIDOS
PEARL JAM|ESTADOS UNIDOS
AEROSMITH|ESTADOS UNIDOS
FOO FIGHTERS|ESTADOS UNIDOS
AC/DC|AUSTRALIA
INXS|AUSTRALIA
BEE GEES|AUSTRALIA
CROWDED HOUSE|AUSTRALIA
MIDNIGHT OIL|AUSTRALIA
MEN AT WORK|AUSTRALIA
TAME IMPALA|AUSTRALIA
5 SECONDS OF SUMMER|AUSTRALIA
THE AVALANCHES|AUSTRALIA
SILVERCHAIR|AUSTRALIA
ABBA|SUECIA
ROXETTE|SUECIA
EUROPE|SUECIA
ACE OF BASE|SUECIA
THE CARDIGANS|SUECIA
GHOST|SUECIA
MESHUGGAH|SUECIA
KENT|SUECIA
OPETH|SUECIA
THE HIVES|SUECIA
`,

    M3E3: `

#TITULO
Mundo 3 - Etapa 3

#INSTRUCCION
Asocia las siguientes CANCIONES al GRUPO MUSICAL que le corresponde

#ENCABEZADO
CANCIÓN|GRUPO MUSICAL

#DATOS
DE MÚSICA LIGERA|SODA STEREO
CUANDO PASE EL TEMBLOR|SODA STEREO
PERSIANA AMERICANA|SODA STEREO
TRATAME SUAVEMENTE|SODA STEREO
NADA PERSONAL|SODA STEREO
EN LA CIUDAD DE LA FURIA|SODA STEREO
SIGNOS|SODA STEREO
JUEGOS DE SEDUCCIÓN|SODA STEREO
PRIMAVERA 0|SODA STEREO
ZOOM|SODA STEREO
IMÁGENES PAGANAS|VIRUS
SUPERFICIES DE PLACER|VIRUS
PRONTA ENTREGA|VIRUS
ME PUEDO PROGRAMAR|VIRUS
WADU WADU|VIRUS
SIN DISFRAZ|VIRUS
UNA LUNA DE MIEL EN LA MANO|VIRUS
EL PROBADOR|VIRUS
ENTRÉGATE|VIRUS
AMOR DESCARTABLE|VIRUS
LA MURALLA VERDE|LOS ENANITOS VERDES
LAMENTO BOLIVIANO|LOS ENANITOS VERDES
TE VI EN UN TREN|LOS ENANITOS VERDES
IGUAL QUE AYER|LOS ENANITOS VERDES
AMORES LEJANOS|LOS ENANITOS VERDES
POR EL RESTO|LOS ENANITOS VERDES
CADA VEZ QUE DIGO ADIÓS|LOS ENANITOS VERDES
MI PRIMER DÍA SIN TI|LOS ENANITOS VERDES
TU CÁRCEL|LOS ENANITOS VERDES
AÚN SIGO CANTANDO|LOS ENANITOS VERDES
SIEMPRE FUISTE MI AMOR|GIT
LA CALLE ES SU LUGAR|GIT
ES POR AMOR|GIT
GRITAR|GIT
SOLO UNA NOCHE MÁS|GIT
BRILLANDO|GIT
MÁS DE LO QUE IMAGINAS|GIT
PENSAR EN TI|GIT
TENGO TU AMOR|GIT
QUIERO DECIRTE QUE TE AMO|GIT
`,

    M3E4: `

#TITULO
Mundo 3 - Etapa 4

#INSTRUCCION
Asocia las siguientes CANCIONES al GRUPO MUSICAL que le corresponde

#ENCABEZADO
CANCIÓN|GRUPO MUSICAL

#DATOS
GOOD VIBRATIONS|BEACH BOYS
GOD ONLY KNOWS|BEACH BOYS
WOULDN'T IT BE NICE|BEACH BOYS
CALIFORNIA GIRLS|BEACH BOYS
SURFIN' U.S.A.|BEACH BOYS
DON'T WORRY BABY|BEACH BOYS
I GET AROUND|BEACH BOYS
KOKOMO|BEACH BOYS
HELP ME, RHONDA|BEACH BOYS
SLOOP JOHN B|BEACH BOYS
LIGHT MY FIRE|THE DOORS
RIDERS ON THE STORM|THE DOORS
BREAK ON THROUGH|THE DOORS
THE END|THE DOORS
PEOPLE ARE STRANGE|THE DOORS
L.A. WOMAN|THE DOORS
LOVE ME TWO TIMES|THE DOORS
TOUCH ME|THE DOORS
HELLO, I LOVE YOU|THE DOORS
ROADHOUSE BLUES|THE DOORS
HOTEL CALIFORNIA|EAGLES
TAKE IT EASY|EAGLES
DESPERADO|EAGLES
NEW KID IN TOWN|EAGLES
ONE OF THESE NIGHTS|EAGLES
LIFE IN THE FAST LANE|EAGLES
LYIN' EYES|EAGLES
TEQUILA SUNRISE|EAGLES
PEACEFUL EASY FEELING|EAGLES
HEARTACHE TONIGHT|EAGLES
FORTUNATE SON|CREEDENCE CLEARWATER REVIVAL
BAD MOON RISING|CREEDENCE CLEARWATER REVIVAL
PROUD MARY|CREEDENCE CLEARWATER REVIVAL
HAVE YOU EVER SEEN THE RAIN|CREEDENCE CLEARWATER REVIVAL
DOWN ON THE CORNER|CREEDENCE CLEARWATER REVIVAL
BORN ON THE BAYOU|CREEDENCE CLEARWATER REVIVAL
GREEN RIVER|CREEDENCE CLEARWATER REVIVAL
LOOKIN' OUT MY BACK DOOR|CREEDENCE CLEARWATER REVIVAL
RUN THROUGH THE JUNGLE|CREEDENCE CLEARWATER REVIVAL
WHO'LL STOP THE RAIN|CREEDENCE CLEARWATER REVIVAL
`,

    M3E5: `

#TITULO
Mundo 3 - Etapa 5

#INSTRUCCION
Asocia cada GRUPO MUSICAL a su PAÍS de origen

#ENCABEZADO
GRUPO|PAÍS

#DATOS
MECANO|ESPAÑA
HÉROES DEL SILENCIO|ESPAÑA
LA OREJA DE VAN GOGH|ESPAÑA
RADIO FUTURA|ESPAÑA
EXTREMODURO|ESPAÑA
LOS SECRETOS|ESPAÑA
NACHA POP|ESPAÑA
JARABE DE PALO|ESPAÑA
AMARAL|ESPAÑA
EL CANTO DEL LOCO|ESPAÑA
MANÁ|MÉXICO
CAFÉ TACVBA|MÉXICO
MOLOTOV|MÉXICO
CAIFANES|MÉXICO
ZOÉ|MÉXICO
EL TRI|MÉXICO
LOS TIGRES DEL NORTE|MÉXICO
RBD|MÉXICO
REIK|MÉXICO
PANTEÓN ROCOCÓ|MÉXICO
SODA STEREO|ARGENTINA
PATRICIO REY Y SUS REDONDITOS DE RICOTA|ARGENTINA
LOS FABULOSOS CADILLACS|ARGENTINA
BABASÓNICOS|ARGENTINA
LOS ENANITOS VERDES|ARGENTINA
VIRUS|ARGENTINA
SUMO|ARGENTINA
SERÚ GIRÁN|ARGENTINA
LOS AUTÉNTICOS DECADENTES|ARGENTINA
MIRANDA!|ARGENTINA
LEGIÃO URBANA|BRASIL
OS MUTANTES|BRASIL
TITÃS|BRASIL
PARALAMAS DO SUCESSO|BRASIL
BARÃO VERMELHO|BRASIL
SKANK|BRASIL
SEPULTURA|BRASIL
ROUPA NOVA|BRASIL
JOTA QUEST|BRASIL
TRIBALISTAS|BRASIL
`,

    M4E1: `

#TITULO
Mundo 4 - Etapa 1

#INSTRUCCION
Asocia cada PELÍCULA al DIRECTOR que le corresponde

#ENCABEZADO
PELÍCULA|DIRECTOR

#DATOS
TIBURÓN|STEVEN SPIELBERG
E.T., EL EXTRATERRESTRE|STEVEN SPIELBERG
INDIANA JONES Y LOS CAZADORES DEL ARCA PERDIDA|STEVEN SPIELBERG
PARQUE JURÁSICO|STEVEN SPIELBERG
LA LISTA DE SCHINDLER|STEVEN SPIELBERG
THX 1138|GEORGE LUCAS
AMERICAN GRAFFITI|GEORGE LUCAS
LA GUERRA DE LAS GALAXIAS: UNA NUEVA ESPERANZA|GEORGE LUCAS
LA GUERRA DE LAS GALAXIAS: LA AMENAZA FANTASMA|GEORGE LUCAS
LA GUERRA DE LAS GALAXIAS: LA VENGANZA DE LOS SITH|GEORGE LUCAS
VOLVER AL FUTURO|ROBERT ZEMECKIS
¿QUIÉN ENGAÑÓ A ROGER RABBIT?|ROBERT ZEMECKIS
FORREST GUMP|ROBERT ZEMECKIS
CONTACTO|ROBERT ZEMECKIS
NÁUFRAGO|ROBERT ZEMECKIS
EL EXTERMINADOR|JAMES CAMERON
ALIENS|JAMES CAMERON
MENTIRAS VERDADERAS|JAMES CAMERON
TITANIC|JAMES CAMERON
AVATAR|JAMES CAMERON
`,

    M4E2: `

#TITULO
Mundo 4 - Etapa 2

#INSTRUCCION
Asocia cada PELÍCULA al DIRECTOR que le corresponde

#ENCABEZADO
PELÍCULA|DIRECTOR

#DATOS
TAXI DRIVER|MARTIN SCORSESE
BUENOS MUCHACHOS|MARTIN SCORSESE
CASINO|MARTIN SCORSESE
LOS INFILTRADOS|MARTIN SCORSESE
EL LOBO DE WALL STREET|MARTIN SCORSESE
JUEGOS, TRAMPAS Y DOS ARMAS HUMEANTES|GUY RITCHIE
SNATCH: CERDOS Y DIAMANTES|GUY RITCHIE
REVÓLVER|GUY RITCHIE
SHERLOCK HOLMES|GUY RITCHIE
EL AGENTE DE C.I.P.O.L.|GUY RITCHIE
EL MARIACHI|ROBERT RODRIGUEZ
DESPERADO|ROBERT RODRIGUEZ
DEL CREPÚSCULO AL AMANECER|ROBERT RODRIGUEZ
SIN CITY|ROBERT RODRIGUEZ
MACHETE|ROBERT RODRIGUEZ
PERROS DE LA CALLE|QUENTIN TARANTINO
TIEMPOS VIOLENTOS|QUENTIN TARANTINO
HABÍA UNA VEZ EN HOLLYWOOD|QUENTIN TARANTINO
KILL BILL|QUENTIN TARANTINO
BASTARDOS SIN GLORIA|QUENTIN TARANTINO
`,

    M4E3: `

#TITULO
Mundo 4 - Etapa 3

#INSTRUCCION
Asocia cada PELÍCULA al DIRECTOR que le corresponde

#ENCABEZADO
PELÍCULA|DIRECTOR

#DATOS
EL ORIGEN|CHRISTOPHER NOLAN
INTERESTELAR|CHRISTOPHER NOLAN
BATMAN: EL CABALLERO DE LA NOCHE|CHRISTOPHER NOLAN
MEMENTO|CHRISTOPHER NOLAN
DUNKERQUE|CHRISTOPHER NOLAN
EL CLUB DE LA PELEA|DAVID FINCHER
SE7EN, LOS SIETE PECADOS CAPITALES|DAVID FINCHER
ZODIACO|DAVID FINCHER
RED SOCIAL|DAVID FINCHER
PERDIDA|DAVID FINCHER
2001: ODISEA DEL ESPACIO|STANLEY KUBRICK
EL RESPLANDOR|STANLEY KUBRICK
LA NARANJA MECÁNICA|STANLEY KUBRICK
FULL METAL JACKET|STANLEY KUBRICK
OJOS BIEN CERRADOS|STANLEY KUBRICK
PETRÓLEO SANGRIENTO|PAUL THOMAS ANDERSON
MAGNOLIA|PAUL THOMAS ANDERSON
BOOGIE NIGHTS: JUEGOS DE PLACER|PAUL THOMAS ANDERSON
UNA BATALLA TRAS OTRA|PAUL THOMAS ANDERSON
EMBRIAGADO DE AMOR|PAUL THOMAS ANDERSON
`,

    M4E4: `

#TITULO
Mundo 4 - Etapa 4

#INSTRUCCION
Asocia cada PELÍCULA al ACTOR que le corresponde

#ENCABEZADO
PELÍCULA|ACTOR

#DATOS
FORREST GUMP|TOM HANKS
EL NÁUFRAGO|TOM HANKS
RESCATANDO AL SOLDADO RYAN|TOM HANKS
LA TERMINAL|TOM HANKS
SULLY: HAZAÑA EN EL HUDSON|TOM HANKS
TITANIC|LEONARDO DI CAPRIO
EL ORIGEN|LEONARDO DI CAPRIO
EL LOBO DE WALL STREET|LEONARDO DI CAPRIO
REVENANT: EL RENACIDO|LEONARDO DI CAPRIO
LA ISLA SINIESTRA|LEONARDO DI CAPRIO
TOP GUN|TOM CRUISE
MISIÓN IMPOSIBLE|TOM CRUISE
JERRY MAGUIRE|TOM CRUISE
SENTENCIA PREVIA|TOM CRUISE
AL FILO DEL MAÑANA|TOM CRUISE
HOMBRES DE NEGRO|WILL SMITH
DÍA DE LA INDEPENDENCIA|WILL SMITH
SOY LEYENDA|WILL SMITH
EN BUSCA DE LA FELICIDAD|WILL SMITH
ALI|WILL SMITH
`,

    M4E5: `

#TITULO
Mundo 4 - Etapa 5

#INSTRUCCION
Asocia cada PELÍCULA a la ACTRIZ que le corresponde

#ENCABEZADO
PELÍCULA|ACTRIZ

#DATOS
MUJER BONITA|JULIA ROBERTS
ERIN BROCKOVICH|JULIA ROBERTS
NOTTING HILL|JULIA ROBERTS
LA BODA DE MI MEJOR AMIGO|JULIA ROBERTS
NOVIA FUGITIVA|JULIA ROBERTS
LUCY|SCARLETT JOHANSSON
HISTORIA DE UN MATRIMONIO|SCARLETT JOHANSSON
PERDIDOS EN TOKIO|SCARLETT JOHANSSON
BLACK WIDOW|SCARLETT JOHANSSON
LA ISLA|SCARLETT JOHANSSON
MOULIN ROUGE!|NICOLE KIDMAN
LOS OTROS|NICOLE KIDMAN
OJOS BIEN CERRADOS|NICOLE KIDMAN
DOGVILLE|NICOLE KIDMAN
AUSTRALIA|NICOLE KIDMAN
EL CISNE NEGRO|NATALIE PORTMAN
V DE VENDETTA|NATALIE PORTMAN
JACKIE|NATALIE PORTMAN
EL PERFECTO ASESINO|NATALIE PORTMAN
LUCY IN THE SKY|NATALIE PORTMAN
`,

    M5E1: `

#TITULO
Mundo 5 - Etapa 1

#INSTRUCCION
Asocia cada ESCRITOR al PAÍS que le corresponde

#ENCABEZADO
ESCRITOR|PAÍS

#DATOS
LEÓN TOLSTÓI|RUSIA
FIÓDOR DOSTOYEVSKI|RUSIA
ANTÓN CHÉJOV|RUSIA
NIKOLÁI GÓGOL|RUSIA
ALEKSANDR PUSHKIN|RUSIA
MIGUEL DE CERVANTES|ESPAÑA
FEDERICO GARCÍA LORCA|ESPAÑA
MIGUEL DE UNAMUNO|ESPAÑA
FRANCISCO DE QUEVEDO|ESPAÑA
BENITO PÉREZ GALDÓS|ESPAÑA
VICTOR HUGO|FRANCIA
HONORÉ DE BALZAC|FRANCIA
GUSTAVE FLAUBERT|FRANCIA
MOLIÈRE|FRANCIA
STENDHAL|FRANCIA
WILLIAM SHAKESPEARE|INGLATERRA
CHARLES DICKENS|INGLATERRA
JANE AUSTEN|INGLATERRA
GEORGE ORWELL|INGLATERRA
VIRGINIA WOOLF|INGLATERRA
`,

    M5E2: `

#TITULO
Mundo 5 - Etapa 2

#INSTRUCCION
Asocia cada OBRA al ESCRITOR que le corresponde

#ENCABEZADO
OBRA|ESCRITOR

#DATOS
GUERRA Y PAZ|LEÓN TOLSTÓI
ANA KARENINA|LEÓN TOLSTÓI
RESURRECCIÓN|LEÓN TOLSTÓI
LA MUERTE DE IVÁN ILICH|LEÓN TOLSTÓI
LOS COSACOS|LEÓN TOLSTÓI
CRIMEN Y CASTIGO|FIÓDOR DOSTOYEVSKI
LOS HERMANOS KARAMÁZOV|FIÓDOR DOSTOYEVSKI
EL IDIOTA|FIÓDOR DOSTOYEVSKI
LOS DEMONIOS|FIÓDOR DOSTOYEVSKI
MEMORIAS DEL SUBSUELO|FIÓDOR DOSTOYEVSKI
LA GAVIOTA|ANTÓN CHÉJOV
TÍO VANIA|ANTÓN CHÉJOV
LAS TRES HERMANAS|ANTÓN CHÉJOV
EL JARDÍN DE LOS CEREZOS|ANTÓN CHÉJOV
LA DAMA DEL PERRITO|ANTÓN CHÉJOV
EUGENIO ONEGUIN|ALEKSANDR PUSHKIN
LA HIJA DEL CAPITÁN|ALEKSANDR PUSHKIN
BORÍS GODUNOV|ALEKSANDR PUSHKIN
LA DAMA DE PICAS|ALEKSANDR PUSHKIN
LOS RELATOS DE BELKIN|ALEKSANDR PUSHKIN
`,

    M5E3: `
    
#TITULO
Mundo 5 - Etapa 3

#INSTRUCCION
Asocia cada OBRA al ESCRITOR que le corresponde

#ENCABEZADO
OBRA|ESCRITOR

#DATOS
BODAS DE SANGRE|FEDERICO GARCÍA LORCA
LA CASA DE BERNARDA ALBA|FEDERICO GARCÍA LORCA
YERMA|FEDERICO GARCÍA LORCA
ROMANCERO GITANO|FEDERICO GARCÍA LORCA
POETA EN NUEVA YORK|FEDERICO GARCÍA LORCA
NIEBLA|MIGUEL DE UNAMUNO
SAN MANUEL BUENO, MÁRTIR|MIGUEL DE UNAMUNO
ABEL SÁNCHEZ|MIGUEL DE UNAMUNO
DEL SENTIMIENTO TRÁGICO DE LA VIDA|MIGUEL DE UNAMUNO
LA TÍA TULA|MIGUEL DE UNAMUNO
LA VIDA DEL BUSCÓN|FRANCISCO DE QUEVEDO
SUEÑOS Y DISCURSOS|FRANCISCO DE QUEVEDO
LA CUNA Y LA SEPULTURA|FRANCISCO DE QUEVEDO
POLÍTICA DE DIOS, GOBIERNO DE CRISTO|FRANCISCO DE QUEVEDO
EL PARNASO ESPAÑOL|FRANCISCO DE QUEVEDO
FORTUNATA Y JACINTA|BENITO PÉREZ GALDÓS
MISERICORDIA|BENITO PÉREZ GALDÓS
DOÑA PERFECTA|BENITO PÉREZ GALDÓS
MARIANELA|BENITO PÉREZ GALDÓS
EPISODIOS NACIONALES|BENITO PÉREZ GALDÓS
`,

    M5E4: `

#TITULO
Mundo 5 - Etapa 4

#INSTRUCCION
Asocia cada OBRA al ESCRITOR que le corresponde

#ENCABEZADO
OBRA|ESCRITOR

#DATOS
LOS MISERABLES|VICTOR HUGO
NUESTRA SEÑORA DE PARÍS|VICTOR HUGO
EL HOMBRE QUE RÍE|VICTOR HUGO
NOVENTA Y TRES|VICTOR HUGO
LAS CONTEMPLACIONES|VICTOR HUGO
LA COMEDIA HUMANA|HONORÉ DE BALZAC
PAPÁ GORIOT|HONORÉ DE BALZAC
EUGENIA GRANDET|HONORÉ DE BALZAC
LAS ILUSIONES PERDIDAS|HONORÉ DE BALZAC
LA PRIMA BETTE|HONORÉ DE BALZAC
MADAME BOVARY|GUSTAVE FLAUBERT
LA EDUCACIÓN SENTIMENTAL|GUSTAVE FLAUBERT
SALAMBÓ|GUSTAVE FLAUBERT
TRES CUENTOS|GUSTAVE FLAUBERT
LA TENTACIÓN DE SAN ANTONIO|GUSTAVE FLAUBERT
TARTUFO|MOLIÈRE
EL AVARO|MOLIÈRE
EL MISÁNTROPO|MOLIÈRE
EL ENFERMO IMAGINARIO|MOLIÈRE
LAS PRECIOSAS RIDÍCULAS|MOLIÈRE
`,

    M5E5: `

#TITULO
Mundo 5 - Etapa 5

#INSTRUCCION
Asocia cada OBRA al ESCRITOR que le corresponde

#ENCABEZADO
OBRA|ESCRITOR

#DATOS
HAMLET|WILLIAM SHAKESPEARE
ROMEO Y JULIETA|WILLIAM SHAKESPEARE
MACBETH|WILLIAM SHAKESPEARE
OTELO|WILLIAM SHAKESPEARE
EL REY LEAR|WILLIAM SHAKESPEARE
OLIVER TWIST|CHARLES DICKENS
CUENTO DE NAVIDAD|CHARLES DICKENS
DAVID COPPERFIELD|CHARLES DICKENS
GRANDES ESPERANZAS|CHARLES DICKENS
HISTORIA DE DOS CIUDADES|CHARLES DICKENS
ORGULLO Y PREJUICIO|JANE AUSTEN
SENTIDO Y SENSIBILIDAD|JANE AUSTEN
EMMA|JANE AUSTEN
MANSFIELD PARK|JANE AUSTEN
PERSUASIÓN|JANE AUSTEN
LA SEÑORA DALLOWAY|VIRGINIA WOOLF
AL FARO|VIRGINIA WOOLF
ORLANDO|VIRGINIA WOOLF
LAS OLAS|VIRGINIA WOOLF
UNA HABITACIÓN PROPIA|VIRGINIA WOOLF
`
};
